In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
!pip install numpy scipy matplotlib ipython jupyter pandas sympy nose

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 41.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 69.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.8/385.8 kB 26.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 5.6 MB/s eta 0:00:00
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter-client 6.1.12
    Uninstalling jupyter-client-6.1.12:
      Successfully uninstalled jupyter-client-6.1.12
  Attempting uninstall: jupyter-server
    Found existing installation: jupyter-server 1.24.0
    Uninstalling jupyter-server-1.24.0:
      Successfully uninstalled jupyter-server-1

In [3]:
# 1- Create a 1D NumPy array containing numbers from 0 to 9.

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array:", arr)

Array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
# 2- Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

list = [3.14, 2.17, 0, 1, 2]

# Convert to NumPy array with integer data type
arr = np.array(list, dtype=int)

print("array:", arr)

array: [3 2 0 1 2]


In [5]:
# Exercise 3 : Working with Multi-Dimensional Arrays
# Create a 3x3 NumPy array with values ranging from 1 to 9.

array3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("array:", array3x3)

array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
# Create a 2D NumPy array of shape (4, 5) filled with random numbers.

arr = np.array(np.random.random((4, 5)))
arr

array([[0.9759911 , 0.30890187, 0.18923461, 0.00868589, 0.52474543],
       [0.2963073 , 0.4892926 , 0.81186297, 0.5337605 , 0.86148056],
       [0.92903251, 0.83136166, 0.23696751, 0.91375149, 0.75900174],
       [0.64212151, 0.45589171, 0.15349075, 0.63250216, 0.24286538]])

In [11]:
# Exercise 5 : Indexing Arrays
# Select the second row from a given 2D NumPy array.

# 2D NumPy array
arr = np.array([[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])
print(arr)

# Select the second row (index 1)
second_row = arr[1]

print("Second row:", second_row)

[[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]
Second row: [20 21 22 23 24]


In [12]:
# Exercise 6 : Reversing elements
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

# 1D NumPy array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reverse the order of elements
reversed_arr = arr[::-1]

print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [13]:
# Exercise 7 : Identity Matrix
# Create a 4x4 identity matrix using NumPy.

#4x4 identity matrix
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
# Exercise 8 : Simple Aggregate Funcs
# Find the sum and average of a given 1D array.

# 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])

#the sum of the array
arr_sum = arr.sum()

#the average of the array
arr_average = arr.mean()

print("Sum:", arr_sum)
print("Average:", arr_average)

Sum: 15
Average: 3.0


In [16]:
# Exercise 9 : Create Array and Change its Structure
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

import numpy as np

#NumPy array with elements from 1 to 20
arr = np.arange(1, 21)

# Reshape the array into a 4x5 matrix
reshaped_arr = arr.reshape(4, 5)

print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
# Exercise 10 : Conditional Selection of Values
# Extract all odd numbers from a given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# To extract all odd numbers
odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
