In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [5]:
!pip install numpy scipy matplotlib ipython jupyter pandas sympy nose

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 43.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.8/385.8 kB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 5.9 MB/s eta 0:00:00
  Attempting uninstall: jupyter-client
    Found existing installation: jupyter-client 6.1.12
    Uninstalling jupyter-client-6.1.12:
      Successfully uninstalled jupyter-client-6.1.12
  Attempting uninstall: jupyter-server
    Found existing installation: jupyter-server 1.24.0
    Uninstalling jupyter-server-1.24.0:
      Successfully uninstalled jupyter-server-1

In [6]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [10]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

1D Array: [1 2 3 4 5]


In [8]:
# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

2D Array:
 [[1 2 3]
 [4 5 6]]


In [9]:
# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

Shape: (2, 3)
Size: 6
Data Type: int64


In [11]:
# Create an array with numbers 1 to 3 as floats
arr = np.array([1, 2, 3], dtype=float)

# Print the array
print("Array:", arr)

# Check and print the data type
print("Data Type:", arr.dtype)

Array: [1. 2. 3.]
Data Type: float64


In [12]:
# # Exercise: Create the following arrays:

# A one dimensional array with the temperatures from this week.
# Example temperatures in Celsius for the week
temperatures = np.array([15, 17, 14, 18, 20, 16, 19])

print("1D Temperature Array:")
print(temperatures)

1D Temperature Array:
[15 17 14 18 20 16 19]


In [13]:
# A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
# 2D array (2 rows, 5 columns) with chosen random values between 1 and 10
random_values = np.array([[3, 7, 2, 9, 5], [6, 1, 8, 4, 10]])

print("\n2D Random Array (2x5):")
print(random_values)


2D Random Array (2x5):
[[ 3  7  2  9  5]
 [ 6  1  8  4 10]]


In [15]:
# A 3D array with valid pixel values for a picture with 9 pixels.
# 3D array representing 9 pixels (3x3) with RGB values (0-255)

REDO THIS
pixels = np.random.randint(0, 256, size=(3, 3, 3))

print("\n3D Pixel Array (3x3, RGB Values):")
print(pixels)


3D Pixel Array (3x3, RGB Values):
[[[ 38 253 239]
  [139 156 105]
  [ 65   7 151]]

 [[ 24 206  23]
  [ 25  94  79]
  [ 64 222 154]]

 [[ 54 132 124]
  [148 122 235]
  [132 118 165]]]


In [16]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [17]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

Element at row 1, column 2: 6


In [19]:
# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

Second row: [4 5 6]


In [20]:
# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Third column: [3 6 9]


In [21]:
# Comprehensive Teaching of Slicing
# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [ ]:
# Note on Advanced Indexing and Shapes
# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array