Exercise 1 : Small Quizz
1- What is the key difference between traditional machine learning and deep learning? Traditional machine learning needs humans to choose important data features, while deep learning figures them out on its own using neural networks. This makes deep learning better for complex (unstructured) data like images, speech, and text.
2- How do artificial neural networks (ANNs) mimic the human brain? ANNs work like a simplified version of the human brain. They have neurons (nodes) that are connected by weights (like brain synapses). These neurons process information, learn patterns, and improve over time—just like how our brains learn from experience.
3- Why does deep learning perform better on large datasets compared to traditional machine learning? Deep learning gets better as it sees more data because its neural networks learn complex patterns. Traditional machine learning struggles with too much data since it relies on human-selected features, while deep learning automatically finds the best features from large datasets.
4- What are some challenges of deep learning, and how can they be addressed?
a-Needs a lot of data → Solution: we could use data augmentation or pre-trained models.
b-Computationally expensive → we could use GPUs/TPUs or cloud computing.
c-Hard to understand (black box problem) → we could use Explainable AI (XAI) tools.
d-Overfitting (memorizing instead of learning) → we could use dropout, regularization, or more data.
5- What is feature engineering, and why is it not needed in deep learning? Feature engineering is the process of manually selecting important data features for a machine learning model. In deep learning, this step is not needed because neural networks automatically learn the best features from raw data, making the process more efficient, especially for complex data like images and text.
6- What role do hidden layers play in a deep learning model? Hidden layers process and transform data step by step, learning increasingly complex patterns.Early layers detect simple patterns (e.g., edges in an image).
Middle layers recognize structures (e.g., eyes, wheels).
Deeper layers understand high-level concepts (e.g., a face, a car).
More hidden layers = better learning but more computing power needed.
7- In an artificial neural network (ANN), what is the function of an activation function? An activation function decides whether a neuron should be "activated" (turned on) or not. It helps the network learn complex patterns by adding non-linearity, meaning the model can handle real-world problems instead of just making simple calculations.
Exemples: ReLU → Most common, keeps positive values and sets negatives to zero.
Sigmoid → Converts values to a range between 0 and 1 (good for probabilities).
Tanh → Similar to Sigmoid but outputs between -1 and 1.


In [1]:
# Exercise 2 : Building a Simple Perceptron Decision System
Temperature_weight = 0.6
Rain_weight = 0.4
Bias = 2

# Compute the weighted sum using the formula:
# Weighted_Sum=(Temperature×0.6)+(Rain×0.4)+Bias
# Weighted_Sum=(Temperature×0.6)+(Rain×0.4)+Bias

# Step Activation Function:
# If Weighted Sum > 20, output 1 (Yes, go outside).
# If Weighted Sum ≤ 20, output 0 (No, stay inside).


# Case 1:
Temperature = 70
Rain = 0

Sum= (Temperature*Temperature_weight)+(Rain*Rain_weight)+Bias
print(Sum)
# Sum= (70*0.6)+(0*0.4)+2


44.0


In [2]:
# Case 2:
Temperature2 = 50
Rain2 = 1
Sum= (Temperature2*Temperature_weight)+(Rain2*Rain_weight)+Bias
print(Sum)
# Sum= (50*0.6)+(1*0.4)+2

32.4


In [3]:
# 2. Interpret the results: Did the perceptron suggest going outside in both cases? Why or why not?



In [4]:
# Exercise 3 : Building a Simple Neural Network with TensorFlow/Keras

# Step1 We import libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.datasets import mnist

# Step2 We import the dataset (x is features y is label)
(x_train, y_train), (x_test, y_test)= keras.datasets.mnist.load_data()

# Step3 Normalize and One-Hot Encode
x_train = x_train / 255.0 #(normalization)
x_test = x_test / 255.0 #(normalization)
print(x_train.shape)
print(x_test)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(60000, 28, 28)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0

In [5]:
# y_train = tf.keras.utils.to_categorical(y_train, num_classes=10) #(Tp do one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

print(y_train.shape)
print(y_test.shape)

(60000, 10)
(10000, 10)


In [6]:
# Step4 Model architectur

My_model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),                          # Flatten the input
    keras.layers.Dense(units=128, activation='relu'),                    # Hidden layer 1 : A layer with 256 neurons and the ReLU activation function.
    keras.layers.Dense(units=10, activation='softmax')                   # Output layer :  Outputs 10 probabilities (one for each class(10 classes in Mnist)).
    ])

print(My_model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten (Flatten)                    │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

None


In [7]:
# Step 5: Compile the Model
My_model.compile(optimizer='adam',
                 loss='sparse_categorical_crossentropy',
                 metrics=['accuracy'])
print(My_model.compile())

# Optimizer: Adam is a popular optimizer that adjusts the weights to minimize the loss.
# Loss Function: Categorical Crossentropy measures how well the model’s predictions match the true labels.
# Metrics: Accuracy is used to evaluate the model’s performance during training.

None


In [19]:
My_model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [20]:
import numpy as np

y_train = np.argmax(y_train, axis=1)  # Convert one-hot encoding to integer labels
y_test = np.argmax(y_test, axis=1)

In [22]:
My_model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [23]:
# Step 6: Train the Model
history = My_model.fit(
    x_train, y_train,  # Training data
    epochs=10,          # Train for 10 epochs
    validation_data=(x_test, y_test)  # We use test data for validation
)
print(history)

# Epochs: The number of times the model sees the entire dataset.
# Steps per Epoch: The number of batches processed in one epoch.
# Validation Data: Used to evaluate the model’s performance during training

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8766 - loss: 0.4401 - val_accuracy: 0.9611 - val_loss: 0.1382
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9654 - loss: 0.1212 - val_accuracy: 0.9716 - val_loss: 0.1012
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9774 - loss: 0.0785 - val_accuracy: 0.9756 - val_loss: 0.0782
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9832 - loss: 0.0566 - val_accuracy: 0.9736 - val_loss: 0.0838
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9861 - loss: 0.0443 - val_accuracy: 0.9757 - val_loss: 0.0756
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9893 - loss: 0.0349 - val_accuracy: 0.9791 - val_loss: 0.0737
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9909 - loss: 0.0281 - val_accuracy: 0.9784 - val_loss: 0.0697
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9945 - loss: 0.02

In [24]:
# Step 7: Make Predictions
Make_predictions = My_model.predict(x_test)
print(Make_predictions)
print(Make_predictions.shape)

# The model outputs a probability distribution for each image.
# For example, [0.1, 0.7, 0.05, …] means the model is 70% confident the image belongs to class 1.

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
[[1.8124562e-09 2.2612604e-12 8.3428390e-08 ... 9.9999911e-01
  7.0103319e-11 2.8458642e-08]
 [4.3940795e-10 1.3596741e-05 9.9998516e-01 ... 7.6287139e-20
  1.1898684e-06 3.3167012e-16]
 [1.5646492e-08 9.9917012e-01 2.1047901e-05 ... 3.2056774e-05
  5.3927070e-04 6.3114351e-07]
 ...
 [2.2213688e-20 1.7245656e-15 1.6216352e-18 ... 4.0741019e-10
  1.0310209e-12 5.5641458e-10]
 [3.4434725e-14 1.6414544e-17 5.5027184e-17 ... 4.2206324e-14
  2.5750662e-06 3.0176922e-17]
 [4.3585628e-09 7.6322514e-15 5.3218333e-11 ... 4.0754861e-17
  1.1779289e-14 3.9742176e-14]]
(10000, 10)


In [25]:
# This is just to make it clearer and To show actual digits
predicted_labels = Make_predictions.argmax(axis=1)
print(predicted_labels)

[7 2 1 ... 4 5 6]


In [26]:
# Step 8: Evaluate the Model’s performance on the test data

test_loss, test_accuracy = My_model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_accuracy:.2f}")

# The model’s accuracy on the test set is 0.98


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9745 - loss: 0.0926
Test Accuracy: 0.98


In [27]:
# Exercise 4 : Forward Propagation Calculation
# Input Values:
x1 = 2000 #(Square Footage)
x2 = 3 #(Number of Bedrooms)
# Initial Weights:
w1 = 0.5 #(Weight for Square Footage)
w2 = 0.7 #(Weight for Bedrooms)
# Bias:
b = 50000
# Activation Function: ReLU (Rectified Linear Unit)

# Each neuron computes a weighted sum of the inputs and applies the ReLU activation function.
# For example, Neuron 1 calculates:



In [13]:
x1

2000

In [14]:
# z= (w1*x1)

In [15]:
# zz = (w2*x2)

In [16]:
b= 50000

In [17]:
z= (w1*x1)+(w2*x2) + b
print(z)

51002.1


In [18]:
# To apply ReLU:
# units is neurons is z in this case
My_model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),                          # Flatten the input                   # Hidden layer 1 : A layer with 256 neurons and the ReLU activation function.
    keras.layers.Dense(units=z, activation='softmax')                   # Output layer :  Outputs 10 probabilities (one for each class(10 classes in Mnist)).
    ])
print(My_model.summary())

ValueError: Cannot convert '(784, 51002.1)' to a shape. Found invalid entry '51002.1' of type '<class 'float'>'. 